// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ContentLoaderController from "./content_loader_controller"
application.register("content-loader", ContentLoaderController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HotelsController from "./hotels_controller"
application.register("hotels", HotelsController)

import SlideshowController from "./slideshow_controller"
application.register("slideshow", SlideshowController)
